- hosts: localhost
  connection: local
  become: true
  vars:
    libvirt_qemu_security_driver: none
    libvirt_qemu_dynamic_ownership: '0'
    libvirt_qemu_remember_owner: '0'
    libvirt_qemu_user: root
    libvirt_qemu_group: wheel
  tasks:
    - name: Install qemu
      community.general.macports:
        name: qemu
        variant: +cocoa+target_arm+target_i386+target_ppc+target_x86_64+usb+vde+vnc
        state: present

    - name: Install libvirt
      community.general.macports:
        name: libvirt
        variant: +qemu
        state: present
    
    # - name: Install vde2 and vde_vmnet
    #   community.general.macports:
    #     name: '{{ item }}'
    #     state: present
    #   with_items:
    #     - vde2
    #     - vde_vmnet

    - name: Set qemu properties for macOS
      template:
        src: etc/libvirt/{{ item + '.j2' }}
        dest: /opt/local/etc/libvirt/{{ item }}
      with_items:
        - qemu.conf
        - libvirtd.conf

    # - name: Ensure /var/run directories exist for vde2
    #   file:
    #     path: /opt/local/var/run/vde2
    #     state: directory
    #     owner: root
    #     group: wheel

    - name: Ensure /var/run directories exist for libvirt
      file:
        path: /opt/local/var/run/libvirt
        state: directory
        owner: root
        group: wheel

    - name: Deploy LaunchDaemons for libvirt # and vde+vmnet
      copy:
        src: Library/LaunchDaemons/{{ item }}
        dest: /Library/LaunchDaemons/{{ item }}
      with_items:
        - com.brad-x.libvirt.libvirtd.plist
        - com.brad-x.libvirt.virtlogd.plist
        # - com.brad-x.vmnet.vde_vmnet.plist
        # - com.brad-x.vmnet.vde2.plist

    - name: Load and start the services
      community.general.launchd:
        name: '{{ item }}'
        enabled: true
        state: started
      with_items:
        - com.brad-x.libvirt.libvirtd
        - com.brad-x.libvirt.virtlogd
        # - com.brad-x.vmnet.vde_vmnet
        # - com.brad-x.vmnet.vde2