instances:
  - name: "Gentoo"
    firmware_type: efi
    cpus: 6
    network_mode: "shared"
    subnet: "10.0.2.0"
    netmask: "255.255.255.0"
    mem: 8G
    disks:
      - name: root
        type: qcow2
        size: 128G
  - name: "FreeBSD"
    firmware_type: efi
    cpus: 6
    network_mode: "shared"
    subnet: "10.0.2.0"
    netmask: "255.255.255.0"
    mem: 8G
    disks:
      - name: root
        type: qcow2
        size: 128G