instances:
  - name: "Windows"
    launchd: false
    config_path: /Users/brad/.qemu/configs
    image_path: /Users/brad/.qemu/images
    firmware_type: efi
    cpus: 6
    cpu_type: qemu64
    display_type: cocoa
    graphics_driver: virtio-vga,edid=off,max_hostmem=1073741824
    network_mode: "shared"
    subnet: "10.0.2.0"
    netmask: "255.255.255.0"
    mem: 8G
    disks:
      - name: root
        type: qcow2
        size: 128G
  - name: "MacOS_9"
    launchd: false
    config_path: /Users/brad/.qemu/configs
    image_path: /Users/brad/.qemu/images
    architecture: ppc
    display_type: cocoa
    cpus: 1
    network_mode: "bridged"
    network_bridge_iface: "en0"
    mem: 256M
    disks:
      - name: root
        type: qcow2
        size: 32G
  - name: "MacOS_X"
    launchd: false
    config_path: /Users/brad/.qemu/configs
    image_path: /Users/brad/.qemu/images
    architecture: ppc
    display_type: cocoa
    cpus: 1
    network_mode: "bridged"
    network_bridge_iface: "en0"
    mem: 256M
    disks:
      - name: root
        type: qcow2
        size: 64G
  - name: "Gentoo"
    launchd: false
    config_path: /Users/brad/.qemu/configs
    image_path: /Users/brad/.qemu/images
    display_type: cocoa
    graphics_driver: virtio-vga,edid=off,max_hostmem=1073741824
    firmware_type: efi
    cpus: 6
    network_mode: "shared"
    subnet: "10.0.2.0"
    netmask: "255.255.255.0"
    mem: 8G
    disks:
      - name: root
        type: qcow2
        size: 128G
  - name: "openSUSE"
    launchd: false
    config_path: /Users/brad/.qemu/configs
    image_path: /Users/brad/.qemu/images
    graphics_driver: virtio-vga,edid=off,max_hostmem=1073741824
    firmware_type: efi
    cpus: 6
    network_mode: "shared"
    subnet: "10.0.2.0"
    netmask: "255.255.255.0"
    mem: 8G
    disks:
      - name: root
        type: qcow2
        size: 128G